package epsilon;

import java.util.List;

import epsilon.commands.Command;

public class Epsilon {
    private Ui ui;
    private Storage storage;
    private Parser parser;
    private TaskList list;

    public Epsilon(String listPath) {
        this.ui = new Ui();
        this.storage = new Storage(listPath);
        List<String> taskInput = storage.readTasks();
        this.list = new TaskList(taskInput);
        this.parser = new Parser();
    }

    /**
     * Takes in user command and sends it to the parser to convert it into a Command.
     * Executes the resulting command.
     *
     * @param cmd String input from the user.
     * @return Returns a response generated by the application based on the command
     *     issued.
     */
    public String getResponse(String cmd) {
        Command c = parser.parse(cmd);
        return c.execute(list, ui, storage);
    }

    public String greet() {
        return ui.welcome();
    }

    /**
     * Terminates the program. Used only when the user closes the program using
     * the close button and not the 'bye' command.
     */
    public void terminate() {
        this.storage.writeTasks(this.list.getRawList());
    }
}
