package epsilon;

import java.time.LocalDate;
import java.util.List;

import epsilon.commands.Command;
import epsilon.tasks.Task;

/**
 * Represents the core functionality of the Epsilon application.
 */
public class Epsilon {
    private Ui ui;
    private Storage storage;
    private Parser parser;
    private TaskList list;

    /**
     * Takes in the path to the file where the tasks are to be stored and
     * creates a new Epsilon object, which represents the core functionality
     * of the application.
     *
     * @param listPath String representing the path to the file that is used to store
     *     the input tasks.
     */
    public Epsilon(String listPath) {
        this.ui = new Ui();
        this.storage = new Storage(listPath);
        List<String> taskInput = storage.readTasks();
        this.list = new TaskList(taskInput);
        this.parser = new Parser();
    }

    /**
     * Takes in user command and sends it to the parser to convert it into a Command.
     * Executes the resulting command.
     *
     * @param cmd String input from the user.
     * @return Returns a response generated by the application based on the command
     *     issued.
     */
    public String getResponse(String cmd) {
        Command command = parser.parse(cmd);
        return command.execute(list, ui, storage);
    }

    /**
     * Returns the standard welcome message.
     *
     * @return String that contains a welcome message.
     */
    public String greet() {
        String greeting = ui.welcome();
        String upcomingTasks = this.getUpcomingTasks();

        if (upcomingTasks.equals("No tasks found.")) {
            return greeting;
        }

        return greeting + "\n"
            + "---\n"
            + "Here are some of your upcoming tasks:\n"
            + upcomingTasks;
    }

    private String getUpcomingTasks() {
        LocalDate threshhold = LocalDate.now().plusWeeks(1);
        List<Task> upcomingTasks = this.list.getTasksBefore(threshhold);
        return ui.showList(upcomingTasks);
    }

    /**
     * Saves all tasks to hard disk and exits the program.
     * Used only when the user closes the program using the close button
     * and not the 'bye' command.
     */
    public void saveAndExit() {
        this.storage.writeTasks(this.list.getRawList());
    }
}
